# Generated by Django 2.0.2 on 2018-02-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='date',
            field=models.BigIntegerField(default=0),
        ),
    ]
