# Generated by Django 2.0.2 on 2018-02-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_feeling_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='trigger2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feeling',
            name='trigger3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='trigger',
            field=models.CharField(default='', max_length=100),
        ),
    ]
